### ISSUE TITLE
Use of undefined constant STDIN

### ISSUE THREAD

**Issue by mzch** [JulianPrieber/littlelink-custom#236]
Platform: `Debian 11.5`
Server type: `Apache2`
PHP version: `8.1.13`

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)

Updating to v3.1.0, the following error happens while setting up:
`Use of undefined constant STDIN`

The difinition `STDIN` is not in `index.php`.

```diff
--- index.php.orig      2022-11-27 04:10:34.617021695 +0900
+++ index.php   2022-11-27 04:09:04.413053261 +0900
@@ -4,6 +4,7 @@
 use Illuminate\Http\Request;
 
 define('LARAVEL_START', microtime(true));
+define('STDIN',fopen("php://stdin","r"));
 
 /*
 |--------------------------------------------------------------------------
```
- Laravel log
```
[2022-11-26 18:51:31] production.ERROR: Undefined constant "STDIN" {"userId":1,"exception":"[object] (Error(code: 0): Undefined constant \"STDIN\" at /srv/littlelink/littlelink-custom/vendor/symfony/console/Helper/QuestionHelper.php:114)
[stacktrace]
#0 /srv/littlelink/littlelink-custom/vendor/symfony/console/Helper/QuestionHelper.php(68): Symfony\\Component\\Console\\Helper\\QuestionHelper->doAsk()
#1 /srv/littlelink/littlelink-custom/vendor/symfony/console/Style/SymfonyStyle.php(361): Symfony\\Component\\Console\\Helper\\QuestionHelper->ask()
#2 /srv/littlelink/littlelink-custom/vendor/symfony/console/Style/SymfonyStyle.php(279): Symfony\\Component\\Console\\Style\\SymfonyStyle->askQuestion()
#3 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php(133): Symfony\\Component\\Console\\Style\\SymfonyStyle->confirm()
#4 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(29): Illuminate\\Console\\Command->confirm()
#5 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(73): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->confirmToProceed()
#6 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#7 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#11 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#12 /srv/littlelink/littlelink-custom/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#13 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#14 /srv/littlelink/littlelink-custom/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#15 /srv/littlelink/littlelink-custom/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#16 /srv/littlelink/littlelink-custom/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#17 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#18 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Console/Application.php(186): Illuminate\\Console\\Application->run()
#19 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(263): Illuminate\\Console\\Application->call()
#20 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Foundation\\Console\\Kernel->call()
#21 /srv/littlelink/littlelink-custom/app/Http/Controllers/InstallerController.php(101): Illuminate\\Support\\Facades\\Facade::__callStatic()
#22 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\InstallerController->mysqlTest()
#23 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#24 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#25 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#26 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#27 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#28 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#30 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#32 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#34 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#36 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#37 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#39 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#41 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#43 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#44 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#45 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#46 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#47 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#48 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#51 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#54 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#56 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#58 /srv/littlelink/littlelink-custom/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#60 /srv/littlelink/littlelink-custom/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#62 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#64 /srv/littlelink/littlelink-custom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#65 /srv/littlelink/littlelink-custom/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#66 {main}
"} 
```

**Comment by JulianPrieber** [comment]
Does this error show constantly or just after the update?
Can you still use the application?
