### ISSUE TITLE
Updater runs into 500 while finishing

### ISSUE THREAD

**Issue by DunklerPhoenix** [JulianPrieber/littlelink-custom#373]
Platform: `Debian Buster`
Server type: `Docker`
PHP version: `8.1`

Heho again (and again, and again, and ...)

If the updater is started, it comes to a point where it goes to finishing mode.
At this moment it shows for a fraction of a second only a plain white page with the version number and runs into a 500.
A normal page reload later it can finish without any further problems.

I don't know really whats causing this. It also don't happen every time.
![updater](https://user-images.githubusercontent.com/1261305/226735591-22b6b3d2-f66a-4788-b264-140e75fab246.gif)

**Comment by JulianPrieber** [comment]
I need an error message from the error log.
Otherwise, please turn on debugging in your config and try to reproduce the issue.

**Comment by JulianPrieber** [comment]
There is also one in the app itself: /storage/logs/laravel.log

**Comment by DunklerPhoenix** [comment]
laravel.log:


```
[2023-03-21 20:51:39] local.ERROR: There is no notification class that can handle event `Spatie\Backup\Events\BackupWasSuccessful`. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event `Spatie\\Backup\\Events\\BackupWasSuccessful`. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[stacktrace]
#0 /htdocs/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(50): Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent::noNotificationClassForEvent()
#1 /htdocs/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(28): Spatie\\Backup\\Notifications\\EventHandler->determineNotification()
#2 /htdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Spatie\\Backup\\Notifications\\EventHandler->Spatie\\Backup\\Notifications\\{closure}()
#3 /htdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#4 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(451): Illuminate\\Events\\Dispatcher->dispatch()
#5 /htdocs/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(311): event()
#6 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(756): Spatie\\Backup\\Tasks\\Backup\\BackupJob->Spatie\\Backup\\Tasks\\Backup\\{closure}()
#7 /htdocs/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(313): rescue()
#8 /htdocs/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(296): Spatie\\Backup\\Tasks\\Backup\\BackupJob->sendNotification()
#9 /htdocs/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(235): Spatie\\Backup\\Tasks\\Backup\\BackupJob->Spatie\\Backup\\Tasks\\Backup\\{closure}()
#10 /htdocs/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(304): Illuminate\\Support\\Collection->each()
#11 /htdocs/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(168): Spatie\\Backup\\Tasks\\Backup\\BackupJob->copyToBackupDestinations()
#12 /htdocs/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(58): Spatie\\Backup\\Tasks\\Backup\\BackupJob->run()
#13 /htdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\Backup\\Commands\\BackupCommand->handle()
#14 /htdocs/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /htdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /htdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#18 /htdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#19 /htdocs/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute()
#20 /htdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\\Component\\Console\\Command\\Command->run()
#21 /htdocs/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(28): Illuminate\\Console\\Command->run()
#22 /htdocs/vendor/symfony/console/Application.php(1014): Spatie\\Backup\\Commands\\BaseCommand->run()
#23 /htdocs/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#24 /htdocs/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#25 /htdocs/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#26 /htdocs/vendor/laravel/framework/src/Illuminate/Console/Application.php(194): Illuminate\\Console\\Application->run()
#27 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(336): Illuminate\\Console\\Application->call()
#28 /htdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Foundation\\Console\\Kernel->call()
#29 /htdocs/storage/framework/views/2433392ae588db203fd6fa642054a2087444b5d8.php(123): Illuminate\\Support\\Facades\\Facade::__callStatic()
#30 /htdocs/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')
#31 /htdocs/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#32 /htdocs/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#33 /htdocs/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#34 /htdocs/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()
#35 /htdocs/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#36 /htdocs/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#37 /htdocs/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#38 /htdocs/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#39 /htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(906): Illuminate\\Http\\Response->__construct()
#40 /htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(875): Illuminate\\Routing\\Router::toResponse()
#41 /htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Router->prepareResponse()
#42 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#43 /htdocs/app/Http/Middleware/admin.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\admin->handle()
#45 /htdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#47 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#49 /htdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#51 /htdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /htdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#53 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#54 /htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#56 /htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#58 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#60 /htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#61 /htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#62 /htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#63 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#64 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#65 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#67 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#68 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#70 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#71 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#73 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#75 /htdocs/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#77 /htdocs/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fideloper\\Proxy\\TrustProxies->handle()
#79 /htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#81 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#82 /htdocs/index.php(64): Illuminate\\Foundation\\Http\\Kernel->handle()
#83 {main}
"} 
```

**Comment by JulianPrieber** [comment]
`[2023-03-21 20:51:39] local.ERROR: There is no notification class that can handle event `Spatie\Backup\Events\BackupWasSuccessful`. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event `Spatie\\Backup\\Events\\BackupWasSuccessful`. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)`

Does the date and time work out for the issue?

**Comment by DunklerPhoenix** [comment]
yes. 10 min ago (in my timezone +1)

**Comment by JulianPrieber** [comment]
This is a known issue, but this should happen anymore 🤔

**Comment by DunklerPhoenix** [comment]
Ah wait. Sry  this was another error 500 at the second try *facepalm*

**Comment by DunklerPhoenix** [comment]
https://gist.github.com/DunklerPhoenix/103a4f42afce0e911f75c33ee627a9a7

There you have the complete one ^^ I think it was the second from below

**Comment by JulianPrieber** [comment]
These are the ones interesting to us, which one was it?

```
[2023-03-20 14:11:00] local.ERROR: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database (SQL: update "users" set "updated_at" = 2023-03-20 14:11:00 where "id" = 1) {"view":{"view":"/htdocs/resources/views/layouts/sidebar.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): SQLSTATE[HY000]: General error: 8 attempt to write a readonly database (SQL: update \"users\" set \"updated_at\" = 2023-03-20 14:11:00 where \"id\" = 1) at /htdocs/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[2023-03-21 14:43:13] production.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupWasSuccessful. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupWasSuccessful. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 14:43:26] production.ERROR: Undefined constant "STDIN" {"view":{"view":"/htdocs/resources/views/components/finishing.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Undefined constant \"STDIN\" at /htdocs/vendor/symfony/console/Helper/QuestionHelper.php:112)
[2023-03-21 19:31:38] production.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupWasSuccessful. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupWasSuccessful. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 19:31:52] production.ERROR: Undefined constant "STDIN" {"view":{"view":"/htdocs/resources/views/components/finishing.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Undefined constant \"STDIN\" at /htdocs/vendor/symfony/console/Helper/QuestionHelper.php:112)
[2023-03-21 19:34:39] local.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupWasSuccessful. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupWasSuccessful. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:12:26] local.ERROR: Undefined array key "HTTP_USER_AGENT" {"view":{"view":"/htdocs/resources/views/littlelink.blade.php","data":[]},"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Undefined array key \"HTTP_USER_AGENT\" at /htdocs/resources/views/littlelink.blade.php:215)
[2023-03-21 20:17:29] production.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupWasSuccessful. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupWasSuccessful. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:17:42] production.ERROR: Undefined constant "STDIN" {"view":{"view":"/htdocs/resources/views/components/finishing.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Undefined constant \"STDIN\" at /htdocs/vendor/symfony/console/Helper/QuestionHelper.php:112)
[2023-03-21 20:34:12] production.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupHasFailed. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupHasFailed. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:34:12] production.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupHasFailed. {"view":{"view":"/htdocs/resources/views/update.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupHasFailed. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:34:38] production.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupHasFailed. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupHasFailed. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:34:38] production.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupHasFailed. {"view":{"view":"/htdocs/resources/views/update.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupHasFailed. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:34:40] production.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupHasFailed. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupHasFailed. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:34:40] production.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupHasFailed. {"view":{"view":"/htdocs/resources/views/update.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupHasFailed. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:35:37] production.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupWasSuccessful. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupWasSuccessful. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:35:51] production.ERROR: Undefined constant "STDIN" {"view":{"view":"/htdocs/resources/views/components/finishing.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Undefined constant \"STDIN\" at /htdocs/vendor/symfony/console/Helper/QuestionHelper.php:112)
[2023-03-21 20:45:37] local.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupWasSuccessful. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupWasSuccessful. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:50:10] local.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupWasSuccessful. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupWasSuccessful. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
[2023-03-21 20:51:39] local.ERROR: There is no notification class that can handle event Spatie\Backup\Events\BackupWasSuccessful. {"userId":1,"exception":"[object] (Spatie\\Backup\\Exceptions\\NotificationCouldNotBeSent(code: 0): There is no notification class that can handle event Spatie\\Backup\\Events\\BackupWasSuccessful. at /htdocs/vendor/spatie/laravel-backup/src/Exceptions/NotificationCouldNotBeSent.php:13)
```

**Comment by JulianPrieber** [comment]
production.ERROR: Undefined constant "STDIN"

huh?

STDIN isn't even mentioned anywhere in the source code:
https://github.com/JulianPrieber/littlelink-custom/search?q=STDIN&type=code

**Comment by JulianPrieber** [comment]
We had some issue with this one before: `There is no notification class that can handle event Spatie\Backup\Events\BackupWasSuccessful`

This caused your exact problem, and we have no idea why. My main theory is that our backup backend wants to send a message when it's done, but can't because nothing is set up to happen when the update is successful.

So essentially this causes the backup to fail because the backup succeeded...

Since the backup does go through just returns an error message, we suppress that error and handle it silently.

The thing is this would happen before the version with the white blank screen comes up, also as I stated above this shouldn't throw an error 500 anymore. So I don't think this is the error that caused the 500.

**Comment by JulianPrieber** [comment]
A stack trace would be helpfull tough

**Comment by JulianPrieber** [comment]
Not sure why this wouldn't throw an error on every update.

**Comment by JulianPrieber** [comment]
I don't even think this is the issue. If Diving, Laravel article is correct about what's causing this, this part should also silently fail.

**Comment by benhartwich** [comment]
I am having the same issue after an automatic update to the latest version. I´ven´t found any stacktrace at the nginx logs. I´ve rolled back the version from backup.

**Comment by JulianPrieber** [comment]
@benhartwich You rolled back, and the issue happened again, so you can reliably reproduce this issue?

**Comment by benhartwich** [comment]
Yes, this issues occurs everytime I´m trying to update from 3.5.2 -> 3.5.3

**Comment by JulianPrieber** [comment]
Oh, that's great. Are you the only one using this instance?

**Comment by JulianPrieber** [comment]
I think I found what's causing the issue. Would you be able to test some things for me?

**Comment by benhartwich** [comment]
yes, I can test.

**Comment by benhartwich** [comment]
Yes, error 500

**Comment by JulianPrieber** [comment]
Nice! I'll issue a new release in a bit.
